runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/js
  static_dir: static/js
- url: /static/images
  static_dir: static/images
- url: /static/css
  static_dir: static/css
- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest
